# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/calculation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/calculation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18protos/calculation.proto\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x10\x46ibonacciRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"#\n\x11\x46ibonacciResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32k\n\x0c\x43\x61lculations\x12\x34\n\tFibonacci\x12\x11.FibonacciRequest\x1a\x12.FibonacciResponse\"\x00\x12%\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponse\"\x00\x62\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=41,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='PingResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=74,
)


_FIBONACCIREQUEST = _descriptor.Descriptor(
  name='FibonacciRequest',
  full_name='FibonacciRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='FibonacciRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=110,
)


_FIBONACCIRESPONSE = _descriptor.Descriptor(
  name='FibonacciResponse',
  full_name='FibonacciResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='FibonacciResponse.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['FibonacciRequest'] = _FIBONACCIREQUEST
DESCRIPTOR.message_types_by_name['FibonacciResponse'] = _FIBONACCIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'protos.calculation_pb2'
  # @@protoc_insertion_point(class_scope:PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'protos.calculation_pb2'
  # @@protoc_insertion_point(class_scope:PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

FibonacciRequest = _reflection.GeneratedProtocolMessageType('FibonacciRequest', (_message.Message,), {
  'DESCRIPTOR' : _FIBONACCIREQUEST,
  '__module__' : 'protos.calculation_pb2'
  # @@protoc_insertion_point(class_scope:FibonacciRequest)
  })
_sym_db.RegisterMessage(FibonacciRequest)

FibonacciResponse = _reflection.GeneratedProtocolMessageType('FibonacciResponse', (_message.Message,), {
  'DESCRIPTOR' : _FIBONACCIRESPONSE,
  '__module__' : 'protos.calculation_pb2'
  # @@protoc_insertion_point(class_scope:FibonacciResponse)
  })
_sym_db.RegisterMessage(FibonacciResponse)



_CALCULATIONS = _descriptor.ServiceDescriptor(
  name='Calculations',
  full_name='Calculations',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=149,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fibonacci',
    full_name='Calculations.Fibonacci',
    index=0,
    containing_service=None,
    input_type=_FIBONACCIREQUEST,
    output_type=_FIBONACCIRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='Calculations.Ping',
    index=1,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATIONS)

DESCRIPTOR.services_by_name['Calculations'] = _CALCULATIONS

# @@protoc_insertion_point(module_scope)
