# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import calculation_pb2 as protos_dot_calculation__pb2


class CalculationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Fibonacci = channel.unary_unary(
        '/Calculations/Fibonacci',
        request_serializer=protos_dot_calculation__pb2.FibonacciRequest.SerializeToString,
        response_deserializer=protos_dot_calculation__pb2.FibonacciResponse.FromString,
        )
    self.Ping = channel.unary_unary(
        '/Calculations/Ping',
        request_serializer=protos_dot_calculation__pb2.PingRequest.SerializeToString,
        response_deserializer=protos_dot_calculation__pb2.PingResponse.FromString,
        )


class CalculationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Fibonacci(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Fibonacci': grpc.unary_unary_rpc_method_handler(
          servicer.Fibonacci,
          request_deserializer=protos_dot_calculation__pb2.FibonacciRequest.FromString,
          response_serializer=protos_dot_calculation__pb2.FibonacciResponse.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=protos_dot_calculation__pb2.PingRequest.FromString,
          response_serializer=protos_dot_calculation__pb2.PingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculations', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
